# Generated by Django 4.2.16 on 2024-10-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_youtube"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="youtube",
        ),
    ]
