# Generated by Django 4.2.16 on 2024-09-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_excerpt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
    ]
