# Generated by Django 4.2.16 on 2024-10-01 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favourites", "0002_rename_favorite_favourite"),
        ("blog", "0003_remove_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favourites",
            field=models.ManyToManyField(
                related_name="favourites",
                through="favourites.Favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
